[workspace]
resolver = "2"
members = ["crates/cqx", "crates/cqx-rust", "crates/cqx-schema", "crates/cqx-history", "crates/cqx-score", "crates/cqx-store", "crates/cqx-vfs"]
exclude = ["fixtures"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/samifouad/cqx"

[workspace.dependencies]
cqx-schema = { path = "crates/cqx-schema" }
cqx-vfs = { path = "crates/cqx-vfs" }
toml = "0.8"
deka-cli-core = { version = "0.5", default-features = false, features = ["registry"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
syn = { version = "2", features = ["full", "visit", "extra-traits"] }
proc-macro2 = { version = "1", features = ["span-locations"] }
quote = "1"
walkdir = "2"
