use cqx_vfs::Vfs;

fn findings(files: &[(&str, &str)], language: &str, rule: &str) -> u64 {
    let mut vfs = Vfs::new("heavy-layout");
    for (path, source) in files {
        vfs.insert(*path, *source);
    }
    let mut facts = Vec::new();
    let stats = cqx_analysis::run(&vfs, &mut facts).unwrap();
    assert!(stats.unparsed.is_empty(), "{:?}", stats.unparsed);
    let stream = cqx_store::facts::Stream::from_ndjson(&String::from_utf8(facts).unwrap());
    let config = cqx_score::config::Config::from_text(None).unwrap();
    let report = cqx_score::report_json(
        &config,
        &cqx_score::metrics::Metrics::compute(&stream, &config),
    );
    report["rules"]
        .as_array()
        .unwrap()
        .iter()
        .find(|r| r["language"] == language && r["rule"] == rule)
        .and_then(|r| r["total_findings"].as_u64())
        .unwrap_or(0)
}

#[test]
fn heavy_anchored_exclusions_and_real_generated_markers() {
    for (language, extension, manifest, source) in [
        (
            "c",
            "c",
            "CMakeLists.txt",
            "#include <stdlib.h>\nvoid f(void){exit(1);}",
        ),
        (
            "cpp",
            "cpp",
            "CMakeLists.txt",
            "#include <cstdlib>\nvoid f(){std::exit(1);}",
        ),
        (
            "csharp",
            "cs",
            "Library.csproj",
            "class L { void F(){Environment.Exit(1);} }",
        ),
    ] {
        let manifest = format!("nested/{manifest}");
        let product = format!("nested/src/domain/build/Library.{extension}");
        let excluded = format!("nested/build/Library.{extension}");
        let generated = format!("nested/src/Generated.{extension}");
        let ordinary =
            format!("// Values generated by this algorithm; do not edit the result.\n{source}");
        assert_eq!(
            findings(
                &[
                    (&manifest, ""),
                    (&product, &ordinary),
                    (&excluded, source),
                    (&generated, "// @generated\ninvalid source")
                ],
                language,
                "exit-in-library"
            ),
            1
        );
    }
}

#[test]
fn heavy_test_paths_are_anchored_to_projects() {
    for (language, extension, manifest, source) in [
        (
            "c",
            "c",
            "CMakeLists.txt",
            "#include <stdlib.h>\nvoid f(void){exit(1);}",
        ),
        (
            "cpp",
            "cpp",
            "CMakeLists.txt",
            "#include <cstdlib>\nvoid f(){std::exit(1);}",
        ),
        (
            "csharp",
            "cs",
            "Library.csproj",
            "class L { void F(){Environment.Exit(1);} }",
        ),
    ] {
        let manifest = format!("nested/{manifest}");
        let product = format!("nested/src/domain/tests/Library.{extension}");
        let test = format!("nested/tests/Library.{extension}");
        assert_eq!(
            findings(
                &[(&manifest, ""), (&product, source), (&test, source)],
                language,
                "exit-in-library"
            ),
            1
        );
    }
}

#[test]
fn heavy_entries_bound_main_and_nested_helpers() {
    for (language, path, source, expected) in [
        ("c", "main.c", "#include <stdlib.h>\nint main(void){exit(0);} void helper(void){exit(1);}", 1),
        ("cpp", "main.cpp", "#include <cstdlib>\nint main(){std::exit(0);auto nested=[](){std::exit(1);};} void helper(){std::exit(1);}", 2),
        ("csharp", "Main.cs", "class L { static void Main(){Environment.Exit(0); void Nested(){Environment.Exit(1);} } void Helper(){Environment.Exit(1);} }", 2),
        ("csharp", "Main.csx", "Environment.Exit(0); void Helper(){Environment.Exit(1);}", 1),
    ] {
        assert_eq!(findings(&[(path, source)], language, "exit-in-library"), expected, "{language}: {source}");
    }
}

#[test]
fn heavy_specific_codes_stay_quiet_and_broad_suppressions_fire() {
    for (language, path, source) in [
        ("c", "Library.c", "// NOLINT(readability-identifier-naming)\nint x;\n// NOLINT\nint y;\n#pragma clang diagnostic ignored \"-Wconversion\"\n"),
        ("cpp", "Library.cpp", "// NOLINT(readability-identifier-naming)\nint x;\n// NOLINT\nint y;\n"),
        ("csharp", "Library.cs", "#pragma warning disable CS0168\nclass L {}\n#pragma warning disable\n"),
    ] {
        assert_eq!(findings(&[(path, source)], language, "undocumented-suppressions"), 1, "{language}");
    }
}

#[test]
fn directory_discovery_preserves_sibling_sources_in_heavy_output_names() {
    let root =
        std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../fixtures/heavy-discovery");
    let vfs = cqx_vfs::from_dir(&root).unwrap();
    assert!(vfs.contains("deps/helper.py"));
    assert!(vfs.contains("bin/tool.ts"));
    let files: Vec<_> = vfs.paths().map(|p| (p, vfs.read(p).unwrap())).collect();
    assert_eq!(findings(&files, "python", "exit-in-library"), 1);
    assert_eq!(findings(&files, "typescript", "dynamic-code"), 1);
    assert_eq!(findings(&files, "c", "exit-in-library"), 0);
    assert_eq!(findings(&files, "csharp", "exit-in-library"), 0);
}

#[test]
fn heavy_c_output_names_are_excluded_only_at_project_roots() {
    for (language, extension, source) in [
        ("c", "c", "#include <stdlib.h>\nvoid f(void){exit(1);}"),
        ("cpp", "cpp", "#include <cstdlib>\nvoid f(){std::exit(1);}"),
    ] {
        for marker in ["CMakeLists.txt", "Makefile", "meson.build", "configure.ac"] {
            for root in ["", "nested/"] {
                for directory in ["out", "external", "deps"] {
                    let marker = format!("{root}{marker}");
                    let product = format!("{root}src/{directory}/Library.{extension}");
                    let excluded = format!("{root}{directory}/Library.{extension}");
                    assert_eq!(
                        findings(
                            &[(&marker, ""), (&product, source), (&excluded, source)],
                            language,
                            "exit-in-library"
                        ),
                        1,
                        "{product}"
                    );
                }
            }
        }
    }
}

#[test]
fn heavy_diagnostic_prose_without_a_quoted_code_is_not_a_suppression() {
    for (language, path) in [("c", "Library.c"), ("cpp", "Library.cpp")] {
        for source in [
            "// diagnostic ignored means the compiler skips a check.\nint x;",
            "// The phrase diagnostic ignored is documentation, not a directive.\nint x;",
            "// diagnostic ignored \"all\" is prose.\nint x;",
            "#pragma clang diagnostic ignored\nint x;",
            "#pragma GCC diagnostic ignored \"-Wconversion\"\nint x;",
        ] {
            assert_eq!(
                findings(&[(path, source)], language, "undocumented-suppressions"),
                0,
                "{source}"
            );
        }
        assert_eq!(
            findings(
                &[(path, "#pragma clang diagnostic ignored \"*\"\nint x;")],
                language,
                "undocumented-suppressions"
            ),
            1
        );
    }
}

#[test]
fn heavy_dot_tests_roots_require_a_project_marker_and_exact_suffix() {
    let source = "class L { void F(){Environment.Exit(1);} }";
    for suffix in ["Tests", "Test"] {
        let root = format!("nested/Library.{suffix}");
        let marker = format!("{root}/Library.csproj");
        let path = format!("{root}/Support/Library.cs");
        assert_eq!(
            findings(
                &[(&marker, ""), (&path, source)],
                "csharp",
                "exit-in-library"
            ),
            0
        );
        assert_eq!(findings(&[(&path, source)], "csharp", "exit-in-library"), 1);
    }
    assert_eq!(
        findings(
            &[
                ("nested/Library.TestsExtra/Library.csproj", ""),
                ("nested/Library.TestsExtra/Support/Library.cs", source)
            ],
            "csharp",
            "exit-in-library"
        ),
        1
    );
}
