use cqx_vfs::Vfs;
use serde_json::Value;
fn report(files: &[(&str, &str)]) -> Value {
    let mut vfs = Vfs::new("layout");
    for (p, s) in files {
        vfs.insert(*p, *s);
    }
    let mut facts = Vec::new();
    let stats = cqx_analysis::run(&vfs, &mut facts).unwrap();
    assert!(stats.unparsed.is_empty(), "{:?}", stats.unparsed);
    let stream = cqx_store::facts::Stream::from_ndjson(&String::from_utf8(facts).unwrap());
    let config = cqx_score::config::Config::from_text(None).unwrap();
    cqx_score::report_json(
        &config,
        &cqx_score::metrics::Metrics::compute(&stream, &config),
    )
}
fn count(p: &Value, language: &str, rule: &str) -> u64 {
    p["rules"]
        .as_array()
        .unwrap()
        .iter()
        .find(|r| r["language"] == language && r["rule"] == rule)
        .map_or(0, |r| r["total_findings"].as_u64().unwrap())
}
const CASES: &[(&str, &str, &str, &str)] = &[
    (
        "java",
        "pom.xml",
        "Library.java",
        "class Library { void stop() { System.exit(1); } }",
    ),
    (
        "kotlin",
        "build.gradle.kts",
        "Library.kt",
        "fun stop(){kotlin.system.exitProcess(1)}",
    ),
    (
        "swift",
        "Package.swift",
        "Library.swift",
        "func stop(){exit(1)}",
    ),
    (
        "zig",
        "build.zig",
        "lib.zig",
        "const std=@import(\"std\"); pub fn stop() void {std.process.exit(1);}",
    ),
    (
        "python",
        "pyproject.toml",
        "lib.py",
        "import sys\ndef stop(): sys.exit(1)\n",
    ),
    (
        "php",
        "composer.json",
        "Library.php",
        "<?php function stop(){exit(1);}",
    ),
];
#[test]
fn shared_anchored_exclusions() {
    for &(lang, manifest, name, source) in CASES {
        for dir in ["build", "target", "vendor", "generated"] {
            let marker = format!("modules/app/{manifest}");
            let product = format!("modules/app/src/domain/{dir}/{name}");
            let output = format!("modules/app/{dir}/{name}");
            let p = report(&[(&marker, ""), (&product, source), (&output, source)]);
            assert_eq!(count(&p, lang, "exit-in-library"), 1, "{lang}/{dir}: {p}");
            assert!(p["lines"].as_u64().unwrap() > 0);
        }
        let header = if lang == "python" {
            "# Values generated by this algorithm must not be edited.\n"
        } else if lang == "php" {
            "<?php // Values generated by this algorithm.\n"
        } else {
            "// Values generated by this algorithm; do not edit the result.\n"
        };
        let ordinary = format!(
            "{header}{}",
            if lang == "php" {
                source.trim_start_matches("<?php")
            } else {
                source
            }
        );
        let generated = format!(
            "{}{}",
            if lang == "python" {
                "# @generated\n"
            } else if lang == "php" {
                "<?php\n// @generated\n"
            } else {
                "// @generated\n"
            },
            if lang == "php" {
                source.trim_start_matches("<?php")
            } else {
                source
            }
        );
        let p = report(&[(name, &ordinary)]);
        assert_eq!(count(&p, lang, "exit-in-library"), 1, "ordinary {lang}");
        let p = report(&[(name, &generated), ("quiet.ts", "export const n = 1;")]);
        assert_eq!(count(&p, lang, "exit-in-library"), 0, "marker {lang}");
    }
}
#[test]
fn shared_test_layouts() {
    for &(lang, manifest, name, source) in CASES {
        let test_path = match lang {
            "java" | "kotlin" => format!("module/src/test/{name}"),
            "swift" => format!("module/Tests/{name}"),
            "zig" => "module/lib_test.zig".into(),
            "python" | "php" => format!("module/tests/{name}"),
            _ => unreachable!(),
        };
        let marker = format!("module/{manifest}");
        let product = format!("module/src/domain/tests/{name}");
        let p = report(&[(&marker, ""), (&test_path, source), (&product, source)]);
        assert_eq!(count(&p, lang, "exit-in-library"), 1, "{lang}: {p}");
    }
    for (path, lang, source) in [
        (
            "src/main/Testimonial.kt",
            "kotlin",
            "fun stop(){kotlin.system.exitProcess(1)}",
        ),
        (
            "src/main/CacheTest.kt",
            "kotlin",
            "fun stop(){kotlin.system.exitProcess(1)}",
        ),
        (
            "src/TestHelpers/Library.swift",
            "swift",
            "func stop(){exit(1)}",
        ),
        (
            "src/tests_cache/lib.py",
            "python",
            "import sys\ndef stop(): sys.exit(1)\n",
        ),
        (
            "src/testing/Library.php",
            "php",
            "<?php function stop(){exit(1);}",
        ),
    ] {
        assert_eq!(
            count(&report(&[(path, source)]), lang, "exit-in-library"),
            1,
            "{path}"
        );
    }
}
#[test]
fn shared_scoped_entries() {
    for (lang,path,source,manifest) in [
        ("java","App.java","class App { public static void main(String[] args){System.exit(0);} void helper(){System.exit(1);} }",None),
        ("kotlin","App.kt","fun main(){kotlin.system.exitProcess(0)}\nfun helper(){kotlin.system.exitProcess(1)}",None),
        ("kotlin","App.kts","val status=kotlin.system.exitProcess(0)\nfun helper(){kotlin.system.exitProcess(1)}",None),
        ("swift","main.swift","exit(0)\nfunc helper(){exit(1)}",None),
        ("swift","App.swift","@main struct App { static func main(){exit(0)}; static func helper(){exit(1)} }",None),
        ("zig","main.zig","const std=@import(\"std\"); pub fn main() void {std.process.exit(0);} pub fn helper() void {std.process.exit(1);}",None),
        ("python","app.py","import sys\nif __name__ == '__main__':\n sys.exit(0)\n def helper(): sys.exit(1)\n",None),
        ("python","__main__.py","import sys\nsys.exit(0)\ndef helper(): sys.exit(1)\n",None),
        ("python","pkg/cli.py","import sys\ndef main(): sys.exit(0)\ndef helper(): sys.exit(1)\n",Some(("pkg/pyproject.toml","[project.scripts]\ncli='cli:main'\n"))),
        ("php","public/index.php","<?php exit(0); function helper(){exit(1);}",None),
        ("php","tools/cli.php","<?php exit(0); function helper(){exit(1);}",Some(("composer.json","{\"bin\":[\"tools/cli.php\"]}"))),
    ] {
        let mut files = vec![(path,source)]; if let Some(m) = manifest { files.push(m); }
        assert_eq!(count(&report(&files),lang,"exit-in-library"),1,"{lang}/{path}");
    }
}
#[test]
fn shared_idiomatic_suppressions() {
    for (lang,path,code,n) in [
        ("java","Library.java","class Library { @SuppressWarnings(\"unchecked\") void f() {} @SuppressWarnings(\"all\") void g() {} }",1),
        ("java","Library.java","@SuppressWarnings(\"unchecked\") class Library {}",1),
        ("kotlin","Library.kt","@Suppress(\"UNCHECKED_CAST\") fun f(){}\n@Suppress(\"ALL\") fun g(){}",1),
        ("kotlin","Library.kt","@file:Suppress()\nfun f(){}",1),
        ("kotlin","Library.kt","@Suppress(\"UNCHECKED_CAST\") class Library {}",1),
        ("python","lib.py","x=1 # noqa: E501\ny=2 # type: ignore[attr-defined]\nz=3 # noqa\nw=4 # type: ignore\n",2),
        ("php","Library.php","<?php\n// phpcs:ignore Sniff.Name\n$x=1;\n// phpcs:disable\n$y=2;\n",1),
    ] { assert_eq!(count(&report(&[(path,code)]),lang,"undocumented-suppressions"),n,"{lang}"); }
}
#[test]
fn python_virtualenv_requires_marker_and_outputs_are_anchored() {
    let source = "import sys\ndef stop(): sys.exit(1)\n";
    for dir in [
        "env",
        "cache",
        "venv",
        ".venv",
        "dist",
        ".tox",
        "node_modules",
        "pkg.egg-info",
    ] {
        let path = format!("src/domain/{dir}/lib.py");
        assert_eq!(
            count(&report(&[(&path, source)]), "python", "exit-in-library"),
            1,
            "{path}"
        );
    }
    for path in ["venv/lib.py", ".venv/lib.py", "env/lib.py"] {
        assert_eq!(
            count(&report(&[(path, source)]), "python", "exit-in-library"),
            1,
            "{path}"
        );
    }
    let p = report(&[
        ("src/domain/env/lib.py", source),
        ("src/domain/env/pyvenv.cfg", "home = python"),
        ("quiet.py", "pass\n"),
    ]);
    assert_eq!(p["lines"], 1);
    for dir in [
        "dist",
        ".tox",
        "node_modules",
        "__pycache__",
        "pkg.egg-info",
    ] {
        let path = format!("{dir}/lib.py");
        assert_eq!(
            count(
                &report(&[(&path, source), ("quiet.py", "pass\n")]),
                "python",
                "exit-in-library"
            ),
            0,
            "{path}"
        );
    }
}
#[test]
fn coordinator_layout_crosses_reader_boundaries() {
    let mut full = Vfs::new("layout");
    full.insert("nested/Package.swift", "");
    full.insert("nested/Tests/Helper.swift", "func f(){exit(1)}");
    full.insert("nested/.build/output.swift", "func f(){exit(1)}");
    full.insert(
        "nested/Sources/domain/.build/Library.swift",
        "func f(){exit(1)}",
    );
    let metadata = cqx_analysis::manifests(&full).unwrap();
    full.files.remove("nested/Package.swift");
    let prepared = cqx_analysis::prepare_reporting(&full, metadata, &|_| {}, &|| {}).unwrap();
    let mut gathered = prepared.gathered();
    gathered.resolve();
    let mut facts = Vec::new();
    prepared.emit(&full, &gathered, &mut facts).unwrap();
    let stream = cqx_store::facts::Stream::from_ndjson(&String::from_utf8(facts).unwrap());
    let config = cqx_score::config::Config::from_text(None).unwrap();
    let p = cqx_score::report_json(
        &config,
        &cqx_score::metrics::Metrics::compute(&stream, &config),
    );
    assert_eq!(count(&p, "swift", "exit-in-library"), 1);
    assert_eq!(p["lines"], 1);
}

#[test]
fn filesystem_discovery_obeys_the_shared_model() {
    let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../fixtures/layout-model");
    let vfs = cqx_vfs::from_dir(&root).unwrap();
    for &(lang, manifest, name, _) in CASES {
        assert!(vfs.contains(&format!("{lang}/{manifest}")));
        assert!(vfs.contains(&format!("{lang}/src/domain/build/{name}")));
        assert!(!vfs.contains(&format!("{lang}/build/{name}")));
    }
    assert!(!vfs.contains("python/src/domain/env/lib.py"));
    let out = std::process::Command::new(env!("CARGO_BIN_EXE_cqx"))
        .args(["scan", root.to_str().unwrap(), "--json"])
        .output()
        .unwrap();
    assert!(
        out.status.success(),
        "{}",
        String::from_utf8_lossy(&out.stderr)
    );
    let p: Value = serde_json::from_slice(&out.stdout).unwrap();
    for &(lang, _, _, _) in CASES {
        assert_eq!(count(&p, lang, "exit-in-library"), 1, "{lang}");
    }
    assert!(p["skipped_files"].is_null());
}
