[package]
name = "cqx"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "deka code explorer."

[[bin]]
name = "cqx"
path = "src/main.rs"

[features]
default = []
zega = ["cqx-store/zega"]

[dependencies]
deka-cli-core = { workspace = true }
cqx-rust = { path = "../cqx-rust" }
cqx-store = { path = "../cqx-store" }
cqx-score = { path = "../cqx-score" }
