[package]
name = "cqx-history"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Scores a repository commit by commit."

[dependencies]
cqx-rust = { path = "../cqx-rust" }
cqx-schema = { workspace = true }
cqx-vfs = { workspace = true }
cqx-score = { path = "../cqx-score" }
cqx-store = { path = "../cqx-store" }
cqx-view = { path = "../cqx-view" }
deka-cli-core = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
